import LoginForm from '@/components/modules/auth/login/LoginForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Login | Next Mart',
  description: 'Generated by next mart login page',
};

const LoginPage = () => {
  return (
    <div className="h-screen flex justify-center items-center p-3">
      <LoginForm />
    </div>
  );
};

export default LoginPage;
