import CreateShopForm from '@/components/modules/shop/createShop/CreateShopForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Shop | Next Mart',
  description: 'Generated by next mart create shop page',
};

const CreateShopPage = () => {
  return (
    <div className="flex justify-center items-center p-3">
      <CreateShopForm />
    </div>
  );
};

export default CreateShopPage;
