import RegisterForm from '@/components/modules/auth/register/RegisterForm';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Register | Next Mart',
  description: 'Generated by next mart register page',
};

const RegisterPage = () => {
  return (
    <div className="h-screen flex justify-center items-center p-3">
      <RegisterForm />
    </div>
  );
};

export default RegisterPage;
